FROM odoo:14

# RUN odoo --database=odoo_14_0_remote  --db_user=odoo_14_0_remote_user --db_password=Dyk5vsn7Gs6z1XdG81QSWOTHHbiq9PYU --db_host=dpg-clah11f8im3c73d9b7m0-a --db_port=5432 -i all
CMD odoo --database=odoo_14_0_remote  --db_user=odoo_14_0_remote_user --db_password=Dyk5vsn7Gs6z1XdG81QSWOTHHbiq9PYU --db_host=dpg-clah11f8im3c73d9b7m0-a --db_port=5432 -u ir_attachment
